services:           
  postgres:
    image: postgres:latest       
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: book1234
      POSTGRES_DB: book_db
    ports:
      - "6543:5432"     
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:                      
